version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - add_ssh_keys:
          fingerprints:
            - "34:42:99:b9:a5:2b:6f:4a:e9:ef:b7:22:61:03:17:cf"
      - run:
          name: allow-github
          command: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: clone
          command: git clone $CIRCLE_REPOSITORY_URL .
      - run:
          name: build
          command: 'bash build.sh'