version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - add_ssh_keys
      - run:
          name: allow-github
          command: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: clone
          command: git clone $CIRCLE_REPOSITORY_URL .
      - run:
          name: build
          command: 'bash build.sh'